apiVersion: v1
kind: Namespace
metadata:
  name: ashokitns
---
apiVersion: v1
kind: Pod
metadata:
  name: springbootapppod
  labels:
    app: sbapp #very imp
  namespace: ashokitns
spec:
  containers:
  - name: springbootappcontainer
    image: ashokit/sb-logger-app
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: ashokitns
spec:
  type: LoadBalancer
  selector:
    app: sbapp #pod Label
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30010
...
